# Generated by Django 5.2.5 on 2025-08-20 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создано"),
                            ("in_progress", "В работе"),
                            ("done", "Завершено"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
